'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';

interface JournalEntryLine {
  account: { name: string; type: string };
  debit: number;
  credit: number;
}

interface JournalEntry {
  id: string;
  reference: string;
  date: string;
  journal: { name: string; type: string };
  partner: { name: string } | null;
  status: string;
  sourceType: string;
  lines: JournalEntryLine[];
}

export default function JournalEntriesPage() {
  const router = useRouter();
  const [entries, setEntries] = useState<JournalEntry[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchEntries();
  }, []);

  const fetchEntries = async () => {
    setLoading(true);
    const res = await fetch('/api/journal-entries');
    const data = await res.json();
    setEntries(data);
    setLoading(false);
  };

  const getTotal = (lines: JournalEntryLine[]) =>
    lines.reduce((sum, l) => sum + l.debit, 0);

  const formatSourceType = (type: string) => {
    return type.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
  };

  return (
    <div>
      <div className="page-header">
        <h1>Journal Entries</h1>
        <div className="page-header-actions">
          <span style={{ fontSize: '0.8125rem', color: 'var(--text-muted)', fontStyle: 'italic' }}>
            Read-only — entries are auto-generated by transactions
          </span>
        </div>
      </div>

      <div className="data-table-wrap">
        {loading ? (
          <div className="loading-page"><div className="loading-spinner" /></div>
        ) : entries.length === 0 ? (
          <div className="empty-state">
            <div className="icon">📝</div>
            <h3>No journal entries yet</h3>
            <p>Journal entries are automatically created when you process bills and invoices</p>
          </div>
        ) : (
          <table className="data-table">
            <thead>
              <tr>
                <th>Date</th>
                <th>Reference</th>
                <th>Partner</th>
                <th>Journal</th>
                <th>Source</th>
                <th style={{ textAlign: 'right' }}>Total</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              {entries.map((entry) => (
                <tr key={entry.id} onClick={() => router.push(`/dashboard/journal-entries/${entry.id}`)}>
                  <td>{new Date(entry.date).toLocaleDateString()}</td>
                  <td style={{ color: 'var(--text-primary)', fontWeight: 500, fontFamily: 'monospace' }}>{entry.reference}</td>
                  <td>{entry.partner?.name || '—'}</td>
                  <td>{entry.journal.name}</td>
                  <td style={{ fontSize: '0.75rem' }}>{formatSourceType(entry.sourceType)}</td>
                  <td style={{ textAlign: 'right', fontFamily: 'monospace' }}>₹{getTotal(entry.lines).toLocaleString('en-IN')}</td>
                  <td>
                    <span className="badge badge-posted">{entry.status}</span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  );
}
